# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/clement/projects/Belote

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/clement/projects/Belote

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/clement/projects/Belote/CMakeFiles /home/clement/projects/Belote//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/clement/projects/Belote/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Belote

# Build rule for target.
Belote: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Belote
.PHONY : Belote

# fast build rule for target.
Belote/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/build
.PHONY : Belote/fast

#=============================================================================
# Target rules for targets named Graphique

# Build rule for target.
Graphique: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Graphique
.PHONY : Graphique

# fast build rule for target.
Graphique/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/build
.PHONY : Graphique/fast

src/Carte.o: src/Carte.cpp.o
.PHONY : src/Carte.o

# target to build an object file
src/Carte.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/Carte.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/Carte.cpp.o
.PHONY : src/Carte.cpp.o

src/Carte.i: src/Carte.cpp.i
.PHONY : src/Carte.i

# target to preprocess a source file
src/Carte.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/Carte.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/Carte.cpp.i
.PHONY : src/Carte.cpp.i

src/Carte.s: src/Carte.cpp.s
.PHONY : src/Carte.s

# target to generate assembly for a file
src/Carte.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/Carte.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/Carte.cpp.s
.PHONY : src/Carte.cpp.s

src/Equipe.o: src/Equipe.cpp.o
.PHONY : src/Equipe.o

# target to build an object file
src/Equipe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/Equipe.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/Equipe.cpp.o
.PHONY : src/Equipe.cpp.o

src/Equipe.i: src/Equipe.cpp.i
.PHONY : src/Equipe.i

# target to preprocess a source file
src/Equipe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/Equipe.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/Equipe.cpp.i
.PHONY : src/Equipe.cpp.i

src/Equipe.s: src/Equipe.cpp.s
.PHONY : src/Equipe.s

# target to generate assembly for a file
src/Equipe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/Equipe.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/Equipe.cpp.s
.PHONY : src/Equipe.cpp.s

src/Joueur.o: src/Joueur.cpp.o
.PHONY : src/Joueur.o

# target to build an object file
src/Joueur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/Joueur.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/Joueur.cpp.o
.PHONY : src/Joueur.cpp.o

src/Joueur.i: src/Joueur.cpp.i
.PHONY : src/Joueur.i

# target to preprocess a source file
src/Joueur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/Joueur.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/Joueur.cpp.i
.PHONY : src/Joueur.cpp.i

src/Joueur.s: src/Joueur.cpp.s
.PHONY : src/Joueur.s

# target to generate assembly for a file
src/Joueur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/Joueur.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/Joueur.cpp.s
.PHONY : src/Joueur.cpp.s

src/MainJoueur.o: src/MainJoueur.cpp.o
.PHONY : src/MainJoueur.o

# target to build an object file
src/MainJoueur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/MainJoueur.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/MainJoueur.cpp.o
.PHONY : src/MainJoueur.cpp.o

src/MainJoueur.i: src/MainJoueur.cpp.i
.PHONY : src/MainJoueur.i

# target to preprocess a source file
src/MainJoueur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/MainJoueur.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/MainJoueur.cpp.i
.PHONY : src/MainJoueur.cpp.i

src/MainJoueur.s: src/MainJoueur.cpp.s
.PHONY : src/MainJoueur.s

# target to generate assembly for a file
src/MainJoueur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/MainJoueur.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/MainJoueur.cpp.s
.PHONY : src/MainJoueur.cpp.s

src/PaquetDeCarte.o: src/PaquetDeCarte.cpp.o
.PHONY : src/PaquetDeCarte.o

# target to build an object file
src/PaquetDeCarte.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/PaquetDeCarte.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/PaquetDeCarte.cpp.o
.PHONY : src/PaquetDeCarte.cpp.o

src/PaquetDeCarte.i: src/PaquetDeCarte.cpp.i
.PHONY : src/PaquetDeCarte.i

# target to preprocess a source file
src/PaquetDeCarte.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/PaquetDeCarte.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/PaquetDeCarte.cpp.i
.PHONY : src/PaquetDeCarte.cpp.i

src/PaquetDeCarte.s: src/PaquetDeCarte.cpp.s
.PHONY : src/PaquetDeCarte.s

# target to generate assembly for a file
src/PaquetDeCarte.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/PaquetDeCarte.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/PaquetDeCarte.cpp.s
.PHONY : src/PaquetDeCarte.cpp.s

src/Table.o: src/Table.cpp.o
.PHONY : src/Table.o

# target to build an object file
src/Table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/Table.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/Table.cpp.o
.PHONY : src/Table.cpp.o

src/Table.i: src/Table.cpp.i
.PHONY : src/Table.i

# target to preprocess a source file
src/Table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/Table.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/Table.cpp.i
.PHONY : src/Table.cpp.i

src/Table.s: src/Table.cpp.s
.PHONY : src/Table.s

# target to generate assembly for a file
src/Table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/Table.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/Table.cpp.s
.PHONY : src/Table.cpp.s

src/enums.o: src/enums.cpp.o
.PHONY : src/enums.o

# target to build an object file
src/enums.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/enums.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/enums.cpp.o
.PHONY : src/enums.cpp.o

src/enums.i: src/enums.cpp.i
.PHONY : src/enums.i

# target to preprocess a source file
src/enums.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/enums.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/enums.cpp.i
.PHONY : src/enums.cpp.i

src/enums.s: src/enums.cpp.s
.PHONY : src/enums.s

# target to generate assembly for a file
src/enums.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/enums.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/enums.cpp.s
.PHONY : src/enums.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Belote.dir/build.make CMakeFiles/Belote.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainGraphique.o: src/mainGraphique.cpp.o
.PHONY : src/mainGraphique.o

# target to build an object file
src/mainGraphique.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/mainGraphique.cpp.o
.PHONY : src/mainGraphique.cpp.o

src/mainGraphique.i: src/mainGraphique.cpp.i
.PHONY : src/mainGraphique.i

# target to preprocess a source file
src/mainGraphique.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/mainGraphique.cpp.i
.PHONY : src/mainGraphique.cpp.i

src/mainGraphique.s: src/mainGraphique.cpp.s
.PHONY : src/mainGraphique.s

# target to generate assembly for a file
src/mainGraphique.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphique.dir/build.make CMakeFiles/Graphique.dir/src/mainGraphique.cpp.s
.PHONY : src/mainGraphique.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Belote"
	@echo "... Graphique"
	@echo "... src/Carte.o"
	@echo "... src/Carte.i"
	@echo "... src/Carte.s"
	@echo "... src/Equipe.o"
	@echo "... src/Equipe.i"
	@echo "... src/Equipe.s"
	@echo "... src/Joueur.o"
	@echo "... src/Joueur.i"
	@echo "... src/Joueur.s"
	@echo "... src/MainJoueur.o"
	@echo "... src/MainJoueur.i"
	@echo "... src/MainJoueur.s"
	@echo "... src/PaquetDeCarte.o"
	@echo "... src/PaquetDeCarte.i"
	@echo "... src/PaquetDeCarte.s"
	@echo "... src/Table.o"
	@echo "... src/Table.i"
	@echo "... src/Table.s"
	@echo "... src/enums.o"
	@echo "... src/enums.i"
	@echo "... src/enums.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainGraphique.o"
	@echo "... src/mainGraphique.i"
	@echo "... src/mainGraphique.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

